name: develop build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Testasd on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-20.04]
    steps:
      - name: Git action result notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Testasd on node ${{ matrix.node_version }} and ${{ matrix.os }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
