name: deploy docker image with gcr

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: print variable
      #   run: |
      #     echo $PROJECT_ID $GCE_INSTANCE $GCE_INSTANCE_REGION $KEY

      # - name: checkout
      #   uses: actions/checkout@v2

      # # CD 시작 부분 (GCE 배포 설정)
      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     service_account_key: ${{ secrets.KEY }}
      #     project_id: ${{ secrets.PROJECT_ID }}

      # # GCE Docker 인증
      # - run: |-
      #     gcloud --quiet auth configure-docker

      # # Build the Docker image
      # - name: Build
      #   run: |-
      #     docker build --tag gcr.io/wired-name-354114/yeonhopark .
      # # Push the Docker image to Google Container Registry
      # # Docker image를 Google Container Registry push 함.
      # # 이때 Google Container Registry API 사용 해야함.
      # - name: image push to container registry
      #   run: |-
      #     docker push gcr.io/wired-name-354114/yeonhopark

      - name: Git action result notification
        uses: 8398a7/action-slack@v3
        with:
            status: custom
            fields: workflow,job,commit,repo,ref,author,took
            custom_payload: |
             {
               attachments: [{
                 color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                 text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
               }]
             }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always() # Pick up events even if the job fails or is canceled.
