name: develop build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Testasd on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install
        run: npm install

      - name: tsc
        uses: icrawl/action-tsc@v1

      - name: Git action result notification
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          job_name: Testasd on node ${{ matrix.node_version }} and ${{ matrix.os }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.


      # - name: Notify deployment
      #   uses: 8398a7/action-slack@v3.8.0
      #   with:
      #     status: ${{ job.status }}
      #     author_name: foobarサービスのデプロイ処理結果
      #     fields: repo,message,commit,author,action,job,took,eventName,ref,workflow
      #     mention: "subteam^ユーザーグループID" # 追加
      #     if_mention: failure # 追加
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()
