name: deploy docker image with gcr

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: print variable
      #   run: |
      #     echo $PROJECT_ID $GCE_INSTANCE $GCE_INSTANCE_REGION $KEY

      # - name: checkout
      #   uses: actions/checkout@v2

      # # CD 시작 부분 (GCE 배포 설정)
      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     service_account_key: ${{ secrets.KEY }}
      #     project_id: ${{ secrets.PROJECT_ID }}

      # # GCE Docker 인증
      # - run: |-
      #     gcloud --quiet auth configure-docker

      # # Build the Docker image
      # - name: Build
      #   run: |-
      #     docker build --tag gcr.io/wired-name-354114/yeonhopark .
      # # Push the Docker image to Google Container Registry
      # # Docker image를 Google Container Registry push 함.
      # # 이때 Google Container Registry API 사용 해야함.
      # - name: image push to container registry
      #   run: |-
      #     docker push gcr.io/wired-name-354114/yeonhopark

      - name: Git action result notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
